services:
  frontend:
    build: ./portal_inferencia
    ports: [ "3000:3000" ]

  backend:
    build: ./backend_api
    ports: [ "8000:8000" ]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery:
    build: ./backend_api
    command: celery -A celery_worker worker --loglevel=info
    depends_on: [ redis ]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
